### ISSUE TITLE
al-compositor: fix false grep statement to set vsync

### ISSUE THREAD

**Issue by natemaia** [ARCHLabs/Archlabs-Pipemenus#12]
In al-compositor there is a really simple if statment
```
EXECXCOMP='compton -b'
if glxinfo | egrep -iq 'direct rendering: yes'; then
    EXECXCOMP+=' --vsync opengl'
fi
```
This is great, the problem? It returns false even if you DO have direct rendering
I'd like to test if changing it to works for everyone
```
EXECXCOMP='compton -b'
if glxinfo | egrep -iq 'direct rendering: Yes'; then
    EXECXCOMP+=' --vsync opengl'
fi 
```
This in all theory should make it so that if vsync isn't set in our config but we have access to direct rendering then to enable it without any input on our part..
I just need some others to test the output of 
```
glxinfo | grep 'direct rendering:'
```

**Comment by Dobbie03** [comment]
I get the following response:

`direct rendering: Yes`

**Comment by erikdubois** [comment]
maybe you can find more info over at bunsenlabs
just an idea

**Comment by natemaia** [comment]
Thanks dobbie, I get the same. If we all get the same I'll change it.
That or we can just remove the if statment, as it serves no purpose if we dont want to use it
