### ISSUE TITLE
nvidia-easy-install: start automatically on login

### ISSUE THREAD

**Issue by ydgwgc** [ARCHLabs/Archlabs-Pipemenus#13]
After installing the system, I installed driver for my "VGA compatible controller: NVIDIA Corporation GF119M"  with this scriipt.

But, somehow, it starts automatically every time I login. And I don't know how to disable it.

**Comment by natemaia** [comment]
What WM/DE are you using?


If using openbox, check in ```~/.config/openbox/autostart```
If using i3 check ```~/.config/i3/config```
then try ```/etc/xdg/autostart/*nvidia*.desktop```

You can use the following to see
```
for f in  ~/.config/i3/config ~/.config/i3/config /etc/xdg/autostart/*.desktop; do if grep -qi "nvidia" $f; then echo -e "\nFOUND IN: $f"; grep -i "nvidia" $f; fi
```

Apologies for the delayed response


Cheers,
Nate
