### ISSUE TITLE
al-help-pipemenu

### ISSUE THREAD

**Issue by erikdubois** [ARCHLabs/Archlabs-Pipemenus#2]
these menu's are pointing to chromium
if user does not want users or deletes chromium -- issues
like rest of archlabs replace with exo-open

**Comment by Dobbie03** [comment]
Like you say, the pipe menu will need to be updated showing, exo-open

https://github.com/ARCHLabs/Archlabs-Pipemenus/blob/master/al-help-pipemenu

**Comment by Dobbie03** [comment]
I have updated the pipemenu with exo-open.

**Comment by erikdubois** [comment]
thanks

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by erikdubois** [comment]
tested
works
done
