### ISSUE TITLE
al-hotcorners

### ISSUE THREAD

**Issue by erikdubois** [ARCHLabs/Archlabs-Pipemenus#4]
[link forum](http://archlabs.prophpbb.com/post836.html#p836)

**Comment by Dobbie03** [comment]
So these will need to be added to the next release.

**Comment by erikdubois** [comment]
we should try them out first

**Comment by Dobbie03** [comment]
Delete these, I can't even get them to work.

**Comment by erikdubois** [comment]
ok deleted
