### ISSUE TITLE
Still one ARCHLabs in conky /conky manager help?

### ISSUE THREAD

**Issue by erikdubois** [ARCHLabs/Archlabs-Pipemenus#9]
in menu

**Comment by natemaia** [comment]
I have fixed this along with changing the variables from BL_  to  AL_
tested on both my machines no issues
https://github.com/ARCHLabs/Archlabs-Pipemenus/commit/a51f9d7a138aa503621ecca796c52313ffacecef

**Comment by erikdubois** [comment]
ok double checked
